name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get -y install python-apt
        python -m pip install --upgrade pip
        pip install flask
        pip install flask_httpauth
        pip install pip_api
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint -dR0914,R0912,R0915,R0401,R0801,E0401,E0402,C0206 apt2sbom/*.py
    - name: Attempting install
      run: |
        pip install .
    - name: Test drives
        apt2sbom -y > /dev/null
        apt2sbom -j > /dev/null
        apt2sbom -c > /dev/null
        apt2sbom -c -p > /dev/null
